import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-mainBg">
      <header className="py-5 px-2 flex justify-between border-b border-[#293342] my-3">
        <p className="text-mainText font-bold text-xl flex-1">
          Prompton Gist
        </p>
        <div className="flex justify-end flex-1 gap-3">
          <input
            className="bg-secondBg border border-[#293342] py-1 px-3 rounded-sm text-secondaryText"
            type="search"
            name="gist-search"
            id="gist-search"
            placeholder="Search..."
          />
          <button className="text-mainText bg-buttonBG rounded-sm p-1 px-3">
            All Gists
          </button>
          <button className="text-secondaryText rounded-sm p-1 px-3">
            Back to Home
          </button>
        </div>
      </header>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
